language: java
jdk: openjdk7
before_install:
  - chmod +x prepare-build.sh
  - ./prepare-build.sh 15.0.3
after_success:
  - cd /tmp
  - git clone https://${GH_OAUTH_TOKEN}@github.com/${GH_USER_NAME}/${GH_PROJECT_NAME} PainPoints
  - cd PainPoints
  - cp $TRAVIS_BUILD_DIR/painPoints.jar .
  - git config --global user.name $GIT_AUTHOR_NAME
  - git config --global user.email $GIT_AUTHOR_EMAIL
  - git add painPoints.jar
  - git commit -m "[ci skip] Committed by Travis-CI"
  - git push https://${GH_OAUTH_TOKEN}@github.com/${GH_USER_NAME}/${GH_PROJECT_NAME} 2>&1
  - echo $GH_USER_NAME
  - echo $GH_PROJECT_NAME
env:
  global:
    - secure: wETu7SWmkKXQQI+pe5ypNG+SpJehCWy3pyaQInX30Wndvf+I+c3DOlPvvCB4Xu8m7L+R8x/jfxPFZv4H+JRBkyMKPGdm/9ooVFUfzZ+OZG3ajFyBQPnWy+9+QxqWxuvvKI1OTcgg+Lh1LX8c2vkViEr/qpIQXHEqCj8z0WC9yaM=
    - GH_USER_NAME: schlank
    - GH_PROJECT_NAME: PainPoints
    - GIT_AUTHOR_NAME: "Phil Leder"
    - GIT_AUTHOR_EMAIL: "phil@philipleder.com"
    - CI_HOME=`pwd`/$TRAVIS_REPO_SLUG