language: java
jdk: openjdk7
before_install:
  - chmod +x prepare-build.sh
  - ./prepare-build.sh 15.0.3
after_success:
  - cd /tmp
  - git clone https://${GH_OAUTH_TOKEN}@github.com/${GH_USER_NAME}/${GH_PROJECT_NAME} PainPoints
  - cd PainPoints
  - cp $TRAVIS_BUILD_DIR/build/libs/painPoints.jar .
  - git config --global user.name $GIT_AUTHOR_NAME
  - git config --global user.email $GIT_AUTHOR_EMAIL
  - git add painPoints.jar
  - git commit -m "[ci skip] Committed by Travis-CI"
  - git push https://${GH_OAUTH_TOKEN}@github.com/${GH_USER_NAME}/${GH_PROJECT_NAME} 2>&1
  - echo $GH_USER_NAME
  - echo $GH_PROJECT_NAME
  - chmod +x deployGitHub.sh
  - ./deployGitHub.sh
env:
  global:
    - secure: 96f2751fa7de3ff3b83655cb9ec548a5d935b137
    - GH_USER_NAME: schlank
    - GH_PROJECT_NAME: PainPoints
    - GIT_AUTHOR_NAME: "Phil Leder"
    - GIT_AUTHOR_EMAIL: "phil@philipleder.com"
    - CI_HOME=`pwd`/$TRAVIS_REPO_SLUG